name: tests

on:
  push:
    paths: ['.github/**', 'config/**', 'src/**', 'stubs/**', 'tests/**']
  pull_request:
    paths: ['.github/**', 'config/**', 'src/**', 'stubs/**', 'tests/**']

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        laravel: [5.*, 6.*, 7.*, 8.*]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*
          - laravel: 5.*
            testbench: 3.8.*

    name: PHP ${{ matrix.php }} running Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.6.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Execute tests
        run: composer test
